#!/bin/bash
# Regenerate dcm2mnc test manifests + series.list from a built tree.
#
# Usage:
#   regenerate.sh --build <build-dir> [--data <dcm2niix_data-dir>]
#
# Discovers every leaf DICOM series under each downloaded dcm_qa* repo,
# converts it with dcm2mnc, and writes one <name>.manifest per convertible
# series (geometry + statistics for each produced .mnc), plus series.list
# consumed by Testing/CMakeLists.txt. Series that are JPEG/RLE-compressed
# (known dcm2mnc segfault risk) or that fail to convert are skipped and logged.
#
# The committed manifests are the regression baseline: they pin dcm2mnc's own
# output. Where a dcm2niix reference NIfTI name-matches, centre of mass is
# cross-checked (logged, non-blocking).
set -u

EXPDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD=""; DATA=""
while [ $# -gt 0 ]; do
  case "$1" in
    --build) BUILD="$2"; shift 2 ;;
    --data)  DATA="$2";  shift 2 ;;
    *) echo "unknown arg: $1"; exit 2 ;;
  esac
done
[ -n "$BUILD" ] || { echo "need --build <build-dir>"; exit 2; }
[ -n "$DATA" ] || DATA="$BUILD/minctools/Testing/dcm2niix_data"

find_tool() { find "$BUILD" -name "$1" -type f -executable 2>/dev/null | head -1; }
DCM=$(find_tool dcm2mnc);  MI=$(find_tool mincinfo)
MS=$(find_tool mincstats); N2M=$(find_tool nii2mnc)
for t in "$DCM" "$MI" "$MS"; do
  [ -x "$t" ] || { echo "missing tool (build first?): dcm2mnc/mincinfo/mincstats"; exit 1; }
done

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
LIST="$EXPDIR/series.list"
: > "$LIST"
kept=0; skip_jpeg=0; skip_fail=0

# non-DICOM file filter shared with the test harness
dicom_files() {  # $1 = series dir -> prints DICOM file paths
  find "$1" -maxdepth 1 -type f \
    -not -iname '*.nii'  -not -iname '*.nii.gz' -not -iname '*.json' \
    -not -iname '*.bval' -not -iname '*.bvec'   -not -iname '*.csv' \
    -not -iname '*.xlsx' -not -iname '*.txt'    -not -iname '*.md' \
    -not -iname 'README*' -not -iname '.*'
}

is_compressed() {  # $1 = series dir
  dicom_files "$1" | while read -r f; do
    if grep -qa -e '1.2.840.10008.1.2.4' -e '1.2.840.10008.1.2.5' "$f"; then
      echo yes; return
    fi
  done
}

dump_block() {  # $1 = mnc file ; appends a manifest block to stdout
  local F="$1" d
  echo "file"
  for d in $("$MI" -dimnames "$F" 2>/dev/null); do
    printf 'dim       %-7s %s %s %s\n' "$d" \
      "$("$MI" -dimlength "$d" "$F" 2>/dev/null | tr -d ' ')" \
      "$("$MI" -attvalue "$d:step" "$F" 2>/dev/null | tr -d ' ')" \
      "$("$MI" -attvalue "$d:start" "$F" 2>/dev/null | tr -d ' ')"
  done
  printf 'vartype   %s\n'  "$("$MI" -vartype image "$F" 2>/dev/null | tr -d ' ')"
  printf 'signtype  %s\n'  "$("$MI" -attvalue image:signtype "$F" 2>/dev/null | tr -d ' ')"
  printf 'mean      %s\n'  "$("$MS" -quiet -mean "$F" 2>/dev/null)"
  printf 'stddev    %s\n'  "$("$MS" -quiet -stddev "$F" 2>/dev/null)"
  printf 'com       %s\n'  "$("$MS" -quiet -com -world_only "$F" 2>/dev/null)"
}

process_repo() {  # $1 = repo name
  local repo="$1" root="$DATA/$1/In"
  [ -d "$root" ] || { echo "  (no $root, skipping repo)"; return; }
  # leaf series = dirs that directly contain at least one DICOM file
  dicom_files "$root" >/dev/null 2>&1
  find "$root" -type f | while read -r f; do dirname "$f"; done | sort -u | \
  while read -r dir; do
    # only dirs that actually contain DICOM (non-excluded) files
    local cnt; cnt=$(dicom_files "$dir" | wc -l)
    [ "$cnt" -ge 1 ] || continue
    local rel="${dir#"$DATA/$repo/"}"                 # In/.../series
    local name; name=$(echo "${repo}_${rel#In/}" | tr '/ ' '__' | tr -cd 'A-Za-z0-9_.-')
    if [ -n "$(is_compressed "$dir")" ]; then
      echo "  SKIP(jpeg)  $repo/$rel"; echo "JPEG $repo/$rel" >> "$WORK/skips"; continue
    fi
    local out="$WORK/out_$name"; rm -rf "$out"; mkdir -p "$out"
    if ! dicom_files "$dir" | timeout 120 "$DCM" -clobber -stdin "$out" >/dev/null 2>&1; then
      echo "  SKIP(fail)  $repo/$rel"; echo "FAIL $repo/$rel" >> "$WORK/skips"; continue
    fi
    mapfile -t outs < <(find "$out" -name '*.mnc' | sort)
    if [ "${#outs[@]}" -eq 0 ]; then
      echo "  SKIP(none)  $repo/$rel"; echo "NONE $repo/$rel" >> "$WORK/skips"; continue
    fi
    # write manifest
    local man="$EXPDIR/$name.manifest"
    {
      echo "# $repo/$rel"
      echo "# auto-generated by regenerate.sh -- do not edit by hand"
      echo "n_mnc     ${#outs[@]}"
      local F; for F in "${outs[@]}"; do dump_block "$F"; done
    } > "$man"
    echo "$name|$repo|$rel" >> "$LIST"
    echo "  KEEP        $repo/$rel  (${#outs[@]} mnc)"
    # optional CoM cross-check against name-matching reference
    if [ -x "$N2M" ] && [ "${#outs[@]}" -eq 1 ]; then
      local base ref
      base=$(basename "$rel")
      ref=$(find "$DATA/$repo/Ref" -maxdepth 1 -iname "*$base*.nii" 2>/dev/null | head -1)
      if [ -n "$ref" ]; then
        "$N2M" -clobber "$ref" "$WORK/ref.mnc" >/dev/null 2>&1 && \
          echo "      ref CoM: $("$MS" -quiet -com -world_only "$WORK/ref.mnc")   mnc CoM: $("$MS" -quiet -com -world_only "${outs[0]}")"
      fi
    fi
  done
}

echo "Regenerating dcm2mnc manifests from $DATA"
rm -f "$EXPDIR"/*.manifest
: > "$WORK/skips"
for repo in dcm_qa dcm_qa_nih dcm_qa_uih; do
  echo "== $repo =="
  process_repo "$repo"
done

sort -o "$LIST" "$LIST"
kept=$(wc -l < "$LIST")
skip_jpeg=$(grep -c '^JPEG' "$WORK/skips" 2>/dev/null || echo 0)
skip_fail=$(grep -cvE '^JPEG' "$WORK/skips" 2>/dev/null || echo 0)
echo
echo "SUMMARY: kept=$kept  skipped_jpeg=$skip_jpeg  skipped_other=$skip_fail"
echo "series.list -> $LIST"
