#!/bin/bash
# Regenerate dcm2mnc regression manifests for LOCAL, non-redistributable DICOM
# data (e.g. clinical exports that cannot be downloaded by CI).
#
# Usage:
#   regenerate-local.sh --build <build-dir> --data <local-data-root> \
#                       [--series <name>:<relpath> ...]
#
# <local-data-root> is the directory CMake's MT_DCM2MNC_LOCAL_DATA points at.
# Each --series gives a test name and a path (relative to the data root) of a
# directory holding one DICOM series. If no --series is given, the default set
# below (the CVI BIO0410071 exam) is used.
#
# For each series this converts with dcm2mnc and writes <name>.manifest here
# plus a row "name|relpath" to local.list. Only the manifests and local.list
# are committed; the DICOM data itself stays local. Tests built from these
# files run only when MT_DCM2MNC_LOCAL_DATA is set to a path that exists
# (see Testing/CMakeLists.txt).
set -u

EXPDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD=""; DATA=""
declare -a SERIES=()
while [ $# -gt 0 ]; do
  case "$1" in
    --build)  BUILD="$2"; shift 2 ;;
    --data)   DATA="$2";  shift 2 ;;
    --series) SERIES+=("$2"); shift 2 ;;
    *) echo "unknown arg: $1"; exit 2 ;;
  esac
done
[ -n "$BUILD" ] || { echo "need --build <build-dir>"; exit 2; }
[ -n "$DATA"  ] || { echo "need --data <local-data-root>"; exit 2; }

# Default series: two CVI exams that exercised the dcm2mnc dimension-sizing
# fixes. "ORIG" duplicate series are omitted; they are geometrically identical
# to their non-ORIG counterparts.
#   BIO0410071 - GE 3D Cube + PROPELLER, missing ImagesInAcquisition: drove the
#                slices-vs-time fix (inject Number_of_slices from geometry).
#   BIO0410141 - GE 3D series with CardiacNumberOfImages=0: drove the spurious
#                time=2 fix (treat a 0 time-count as absent).
if [ "${#SERIES[@]}" -eq 0 ]; then
  SERIES=(
    "cvi_bio0410071_sag_t2_flair:BIO0410071_062Y/series0016-unknown"
    "cvi_bio0410071_cor_t1_cube:BIO0410071_062Y/series0018-unknown"
    "cvi_bio0410071_ax_t2_propeller:BIO0410071_062Y/series0019-unknown"
    "cvi_bio0410141_cor_t1_cube:BIO0410141_051Y/series0023-unknown"
    "cvi_bio0410141_sag_t2_flair:BIO0410141_051Y/series0024-unknown"
    "cvi_bio0410141_ax_t2_propeller:BIO0410141_051Y/series0025-unknown"
  )
fi

find_tool() { find "$BUILD" -name "$1" -type f -executable 2>/dev/null | head -1; }
DCM=$(find_tool dcm2mnc);  MI=$(find_tool mincinfo);  MS=$(find_tool mincstats)
for t in "$DCM" "$MI" "$MS"; do
  [ -x "$t" ] || { echo "missing tool (build first?): dcm2mnc/mincinfo/mincstats"; exit 1; }
done

dicom_files() {  # $1 = series dir -> prints DICOM file paths (shared filter)
  find "$1" -maxdepth 1 -type f \
    -not -iname '*.nii'  -not -iname '*.nii.gz' -not -iname '*.json' \
    -not -iname '*.bval' -not -iname '*.bvec'   -not -iname '*.csv' \
    -not -iname '*.xlsx' -not -iname '*.txt'    -not -iname '*.md' \
    -not -iname 'README*' -not -iname '.*'
}

dump_block() {  # $1 = mnc file ; appends a manifest block to stdout
  local F="$1" d
  echo "file"
  for d in $("$MI" -dimnames "$F" 2>/dev/null); do
    printf 'dim       %-7s %s %s %s\n' "$d" \
      "$("$MI" -dimlength "$d" "$F" 2>/dev/null | tr -d ' ')" \
      "$("$MI" -attvalue "$d:step"  "$F" 2>/dev/null | tr -d ' ')" \
      "$("$MI" -attvalue "$d:start" "$F" 2>/dev/null | tr -d ' ')"
  done
  printf 'vartype   %s\n'  "$("$MI" -vartype image "$F" 2>/dev/null | tr -d ' ')"
  printf 'signtype  %s\n'  "$("$MI" -attvalue image:signtype "$F" 2>/dev/null | tr -d ' ')"
  printf 'mean      %s\n'  "$("$MS" -quiet -mean "$F" 2>/dev/null)"
  printf 'stddev    %s\n'  "$("$MS" -quiet -stddev "$F" 2>/dev/null)"
  printf 'com       %s\n'  "$("$MS" -quiet -com -world_only "$F" 2>/dev/null)"
}

WORK=$(mktemp -d); trap 'rm -rf "$WORK"' EXIT
LIST="$EXPDIR/local.list"; : > "$LIST"
kept=0; skipped=0

for entry in "${SERIES[@]}"; do
  name="${entry%%:*}"; rel="${entry#*:}"
  dir="$DATA/$rel"
  if [ ! -d "$dir" ]; then
    echo "  SKIP(no dir)  $rel"; skipped=$((skipped+1)); continue
  fi
  out="$WORK/$name"; rm -rf "$out"; mkdir -p "$out"
  if ! dicom_files "$dir" | "$DCM" -clobber -stdin "$out" >/dev/null 2>&1; then
    echo "  SKIP(fail)    $rel"; skipped=$((skipped+1)); continue
  fi
  mapfile -t outs < <(find "$out" -name '*.mnc' | sort)
  if [ "${#outs[@]}" -eq 0 ]; then
    echo "  SKIP(none)    $rel"; skipped=$((skipped+1)); continue
  fi
  man="$EXPDIR/$name.manifest"
  {
    echo "# $rel"
    echo "# auto-generated by regenerate-local.sh -- do not edit by hand"
    echo "n_mnc     ${#outs[@]}"
    for F in "${outs[@]}"; do dump_block "$F"; done
  } > "$man"
  echo "$name|$rel" >> "$LIST"
  echo "  KEEP          $rel  (${#outs[@]} mnc)"
  kept=$((kept+1))
done

sort -o "$LIST" "$LIST"
echo
echo "SUMMARY: kept=$kept  skipped=$skipped"
echo "local.list -> $LIST"
